### ISSUE TITLE
BUG :: Paste Keyboard Command Not Working on YouTube Blocks on Safari

### ISSUE THREAD

**Issue by albertgcsula** [triniti/cms-js#337]
Users are unable to use the paste (command/ctrl + v) keyboard command on YouTube video blocks on Safari browsers. Other browsers seems to work fine with the keyboard command. In order to paste into the field, you need to right click and hit paste in order for it to work on Safari. I tested and reproduced the issue on Safari version 14.1.2 .

**Comment by albertgcsula** [comment]
@efjacobson not sure if you guys have run into this issue before.

**Comment by efjacobson** [comment]
@albertgcsula not that specifically, no. i initially thought it could be some of the blocksmith keypress stuff but since it is only youtube that seems unlikely. would start by poking around the modal itself to see what is preventing it

after a quick look this seems pretty suspect https://github.com/triniti/cms-js/blob/master/src/plugins/blocksmith/components/youtube-video-block-modal/index.jsx#L179

**Comment by albertgcsula** [comment]
@efjacobson yeah that's weird, looks like this is the only block that has a handleKeyPress method, wonder why that was added for this block specifically. I'll modify the code and do some testing.

**Comment by albertgcsula** [comment]
https://github.com/triniti/cms-js/pull/340
